apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets-external
  namespace: nadun-task-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore

  # This is the K8s secret it will create/update
  target:
    name: app-secrets
    creationPolicy: Owner

  # This maps your GCP secrets to keys in the K8s secret
  data:
    - secretKey: postgres-password # K8s secret key name
      remoteRef:
        key: db-password         # GCP secret name
    - secretKey: jwt-secret          # K8s secret key name
      remoteRef:
        key: jwt-secret          # GCP secret name