apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: nadun-task-app
spec:
  provider:
    gcpsm:
      # Your GCP Project ID
      projectID: "dev-ops-475910"
      auth:
        workloadIdentity:
          # Tell the operator which K8s Service Account to use
          serviceAccountRef:
            name: external-secrets-sa
            namespace: nadun-task-app