apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: nadun-task-app
type: Opaque
stringData:
  jwt-secret: "my-super-secret-jwt-key-change-this-in-production-minimum-256-bits"
  postgres-password: "admin"