apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: nadun-task-app
  annotations:
    # This line links the K8s SA to the GCP SA
    iam.gke.io/gcp-service-account: nadun-github-actions-deployer@dev-ops-475910.iam.gserviceaccount.com