apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: nadun-task-app
type: Opaque
stringData:
  # This secret will be automatically read by the backend deployment
  jwt-secret: "your-super-secret-jwt-key-minimum-256-bits-change-in-production"