apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nadun-task-app-tls
  namespace: nadun-task-app
spec:
  secretName: nadun-task-app-tls # Name of the secret to store the cert
  issuerRef:
    name: letsencrypt-prod # Use the production issuer
    kind: ClusterIssuer
  dnsNames:
    - task_gke.nadunwansooriya.online
    - www.task_gke.nadunwansooriya.online