apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nadun-task-app-ingress
  namespace: nadun-task-app
  annotations:
    # Tell cert-manager to use this Ingress
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    # Tell Ingress to use Nginx
    kubernetes.io/ingress.class: "nginx"

    # Force redirect to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - task_gke.nadunwansooriya.online
        - www.task_gke.nadunwansooriya.online
      secretName: nadun-task-app-tls # Use the secret cert-manager creates
  rules:
    - host: task_gke.nadunwansooriya.online
      http:
        paths:
          - path: /api # Backend traffic
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080 # Port defined in your backend *service*
          - path: /     # All other traffic
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80 # Port defined in your frontend *service*
    - host: www.task_gke.nadunwansooriya.online
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80